<style type="text/css">
	.box{
		background-position: center center;
	    background-repeat: no-repeat;
	    border: 5px solid #CCCCCC;
	    border-radius: 10px 10px 10px 10px;
	    height: 50%;
	    left: 30%;
	    position: fixed;
	    top: 20%;
	    width: 50%;
	    z-index: 9;
		background-image:url("<?php echo Mage::getDesign()->getSkinUrl();?>/images/ajax-loader-tr.gif");
	}
	.box .product-shop{
		float: left;
	    height: 100%;
	    min-height: 100px;
	    width: 48%;
	}
	.box .product-img-box{
		float: left;
	    height: 100%;
	    margin-right: 2%;
	    min-height: 100px;
	    width: 48%;
	}
	.product-img-box img{
		height:100%;
		width:100%;
	}
	.box .product-essential{
		background-color: #FFFFFF;
	    height: 100%;
	}
	.box .product-name{font-size: 1.2em;font-weight: 600;padding: 3px 0;}
	.box .short-description{height: 30%;overflow: auto;margin-bottom:5px;padding:0px}
	.box .description{height: 55%;overflow: auto;}
	.prev{cursor:pointer;left:0px;}
	a.productlink-fix{float:right;margin-right:30px;}
	.wk_cp_button {
	    background-color: #428BCA;
	    border: 1px solid #357EBD;
	    border-radius: 4px;
	    color: #FFFFFF;
	    cursor: pointer;
	    font-size: 14px;
	    line-height: 28px;
	    padding: 5px 10px;
	}
	.wk_cp_button:hover {
	    background-color: #3276B1;
	    border-color: #285E8E;
	}
	#close-prev{
		cursor: pointer;
		color: red;
		font-weight: bold;
	}
</style>
<script type="text/javascript">
	if (typeof jQuery == "undefined")	{
   		 document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
</script>
<script type="text/javascript">
	jQuery.noConflict();
	var inside = "";
	jQuery("#html-body").delegate(".prev","mouseenter mouseout", function(e){
		if(e.type == "mouseenter"){
			inside = jQuery(this).parent().parent().attr("title");
			jQuery(this).parent().parent().attr("title","");
        }
        else
        if(e.type == "mouseout")
			jQuery(this).parent().parent().attr("title", inside);
	});
	jQuery("#html-body").delegate(".prev","click",function(){
		var obj = jQuery("<div class='box'/>");
		jQuery("#html-body").prepend(obj);
		jQuery(".wrapper").css("opacity",".2");
		$currency = "<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?>";
		jQuery(this).attr("data");
		jQuery.ajax({
			url 	 :  jQuery(this).attr("data"),
			data 	 : 	{customerid:jQuery(this).attr("customer-id")},
			dataType : 	"json",
			type 	 : 	"GET",
			success  :  function(data){
				var alt = "",downlink = "",downlink1 = "";
				if(data.url.split("/").length < 2)
					alt = data.url;							
				var tempobj = jQuery("<div/>").addClass("product-essential").append(jQuery("<div/>").addClass("product-img-box").append(jQuery("<img/>").attr("src",data.url).attr("alt",alt))).append(jQuery("<div/>").addClass("product-shop").append(jQuery("<div/>").addClass("product-name").text(data.name).append(downlink1)).append(jQuery("<div/>").addClass("price-box").text("Price :"+$currency+" "+data.price)).append(jQuery("<div/>").addClass("short-description").html(data.short_description)).append(jQuery("<div/>").addClass("description").html(data.description))).append(jQuery("<span/>").text("X").addClass("btn").attr("id","close-prev"));
				obj.append(tempobj);					
			},error    :  function(){
				alert("error");
				jQuery(".box").remove();
				jQuery(".wrapper").css("opacity","1");
			}
		});		
	});			
	jQuery("#html-body").delegate("#close-prev","click",function(){
		jQuery(".box").remove();
		jQuery(".wrapper").css("opacity","1");
	});
</script>