<?php if ($this->getAdditionalContentType()!='' && $this->getAdditionalContentType()!='staticblock'): ?>
	<?php 
		$_productCollection = $this->getAdditionalContent(); 
		$_helper = $this->helper('catalog/output'); 
	?>
	<?php if(count($_productCollection) && Mage::getStoreConfig('ajaxcart/popup_configuration/product_number')!=0): ?>
		<?php if ($this->getAdditionalContentType()=='upsell'): ?>
	    	<h4><?php echo $this->__('You may also be interested in the following product(s)') ?></h4>
	    <?php elseif ($this->getAdditionalContentType()=='related'): ?>
	    	<h4><?php echo $this->__('Related Products') ?></h4> 
	    <?php elseif ($this->getAdditionalContentType()=='crosssell'): ?>
		    <h4><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h4>
	    <?php elseif ($this->getAdditionalContentType()=='new'): ?>
		    <h4><?php echo $this->__('New Products') ?></h4>
		<?php elseif ($this->getAdditionalContentType()=='bestseller'): ?>
		    <h4><?php echo $this->__('Best Selling Products') ?></h4>
		<?php elseif ($this->getAdditionalContentType()=='mostviewed'): ?>
		    <h4><?php echo $this->__('Popular Products') ?></h4>
		<?php endif ?>
	    <div class="ac-product-list">
	    <?php $i=0; foreach ($_productCollection as $_product): ?>
	    	<?php if ($i%2==0): ?>
			<ul class="ajaxcart-products-grid">
			<?php endif ?>
		        <li class="item <?php if ($i%2!=0): ?>last<?php else: ?>first<?php endif ?> disable-dragdrop">
		            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
		            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
		            <?php if($_product->getRatingSummary()): ?>
		            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
		            <?php endif; ?>
		            <?php echo $this->getPriceHtml($_product, true) ?>
		            <div class="actions">
		            	<div id="ac-cart-button<?php echo $_product->getId() ?>">
		                <?php if($_product->isSaleable()): ?>
		                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php echo $this->getAcAddToCartUrl($_product) ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
		                <?php else: ?>
		                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
		                <?php endif; ?>
		                </div>
		                <ul class="add-to-links">
		                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
		                        <li><a href="<?php echo $this->getAcAddToWishlistUrl($_product); ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
		                    <?php endif; ?>
		                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
		                        <li><span class="separator">|</span> <a href="<?php echo $this->getAcAddToCompareUrl($_compareUrl); ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
		                    <?php endif; ?>
		                </ul>
		            </div>
		        </li>
	    	<?php if ($i%2!=0): ?>
			</ul>
			<?php endif ?>
	    <?php $i++; endforeach ?>
	    </div>
	<?php endif ?>
<?php elseif ($this->getAdditionalContentType()=='staticblock'): ?>
	<div id="ac-static-block">
		<?php echo $this->getAdditionalContent(); ?>
	</div>
<?php endif ?>