<?php 	$partner = Mage::getModel("customerpartner/user")->isPartner();
		$helper = Mage::helper("customerpartner");
		if($partner["wantpartner"] == 1)	{ 	
			$readresult = Mage::getModel("customerpartner/saleslist")->getOrderdetails();
			$order_count = count($readresult);
			$getDateDetail = Mage::getModel("customerpartner/saleslist")->getDateDetail();
			$cur_symbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 	?>
			<link href="<?php echo $this->getSkinUrl('customerpartner/css/jquery.jqplot.min.css'); ?>" rel="stylesheet" type="text/css"/>			
			<script src="<?php echo $this->getSkinUrl('customerpartner/js/chart.js'); ?>" type="text/javascript"></script>			
			<div class="wk_cp_productbackground">
				<div class="wk_dashboard">
					<div>
						<h4 style="display:inline-block;" class="wk_cp_product_main_heading"><?php echo $helper->__("Dashboard") ?></h4>
						<button style="width:auto;" class="askque wk_button">
							<span><?php echo $helper->__("Ask Question to Admin") ?></span>
						</button>
					</div>
					<div class="fieldset">
						<h2 class="legend"><?php echo $helper->__("Lifetime Sales") ?></h2>
						<div class="wk_sales">
							 <div class="wk_todaysale"><?php echo Mage::app()->getStore()->formatPrice($getDateDetail[day]);?>&nbsp;
							 	<span class="wk_sale_color">&nbsp;<?php echo $helper->__("Today") ?></span>
							 </div>
							 <div class="wk_weeksale"><?php echo Mage::app()->getStore()->formatPrice($getDateDetail[week]); ?>&nbsp;
							 	<span class="wk_sale_color">&nbsp;<?php echo $helper->__("This Week") ?></span>
							 </div>
							 <div class="wk_monthsale"><?php echo Mage::app()->getStore()->formatPrice($getDateDetail[month]); ?>&nbsp;
								<span class="wk_sale_color"><?php echo $helper->__("This Month") ?></span>
							 </div>
						</div>
					</div>
					<div class="fieldset">
						<h2 class="legend"><?php echo $helper->__("Latest Orders") ?></h2>
						<div class="wk_dash_order">							
<?php 						if($order_count == 0) 	{ 	?>
								<div class="wk_orderbox">
									<div class="wk_emptymsg"><?php echo $helper->__("no order placed yet"); ?></div>
								</div>
<?php 						}	
							$m = 0;$check_for_last = 1;
							foreach($readresult as $res)	{
								$order = Mage::getModel("sales/order")->load($res["mageorderid"]);
								$status = $order->getStatus();
								$name = $order->getCustomerName();
								if($res["mageorderid"] > 0) { 	?>
									<div class="wk_orderbox <?php if($check_for_last == $order_count) echo 'wk_orderbox_last'?>">
										<div class="wk_dash_orderstatus">
											<label for="name" class="wk_dash_label">
<?php 											if($status == "pending") {	?>
													<div class="status" style="background-color:orange"><?php echo strtoupper($helper->__($status)); ?></div>
<?php 											}		?>
<?php 											if($status == "canceled") {	?>
													<div class="status" style="background-color:red"><?php echo strtoupper($helper->__($status)); ?></div>
<?php 											}		?>
<?php 											if($status == "complete") {	?>
													<div class="status" style="background-color:green"><?php echo strtoupper($helper->__($status)); ?></div>
<?php 											}		?>
<?php 											if($status == "processing") {	?>
													<div class="status" style="background-color:blue"><?php echo strtoupper($helper->__($status)); ?></div>
<?php 											} 		?>
												<p style="margin: 0 0 10px 6px;"><?php echo "<br>".$res["cleared_at"]; ?></p> 
											</label> 
										</div>
										<div class="wk_dash_orderstatus">
											<label for="name" class="wk_dash_label">
												<div class="color"><?php echo $helper->__("Order#"); ?><?php echo $res["magerealorderid"]; ?></div>
												<div class="name"><?php echo $helper->__("By"); ?><?php  echo " ".$name; ?>
<?php										    	$pname = explode(",",$res["mageproname"]);
													$pid = explode(",",$res["mageproid"]);
														for($p = 0 ; $p <= count($pid) ; $p++)	{
															if($pname[$p]){
																echo "<p style='color:silver;float:left;'>".$pname[$p]."&nbsp;</p>"; $proid[$m] = $pid[$p];
															}													
														}		?>
												</div> 
											</label> 
										</div>
										<div class="wk_dash_orderstatus">
											<label for="name" class="wk_dash_label" style="float:right;"><?php if($status == "canceled"){ echo Mage::app()->getStore()->formatPrice(0);	}else{ echo Mage::app()->getStore()->formatPrice($res["actualparterprocost"]);}?>
										</div>
									</div>
<?php 							}
								$check_for_last++;
							} 			?>
						</div>
					</div>
					<div class="fieldset">
						<h2 class="legend"><?php echo $helper->__("Latest Reviews & Comments") ?></h2>
						<div class="wk_dash_review">
<?php 						$rate = array();$productId = array();
							$userid = Mage::getSingleton("customer/session")->getCustomerId();
							$reviewcollection = Mage::getModel("customerpartner/product")->getCollection();
							$reviewcollection = $reviewcollection->addFieldToFilter("userid",$userid);
							if(count($reviewcollection)	== 0)	{ 	?>
								<div class="wk_emptymsg"><?php echo $helper->__("no Reviews & Comments"); ?></div>
<?php 						}
							else {
						    	foreach($reviewcollection as $product)
									array_push($productId,$product["mageproductid"]);
								$reviews = Mage::getModel("review/review")->getCollection()->addFieldToFilter("entity_pk_value",$productId)->setOrder("created_at","DESC")->setPageSize(5)->setCurPage(1);
								$review_count = count($reviews);$check_for_last_review = 1;
								if($review_count == 0)	{ 	?>
									<div class="wk_emptymsg"><?php echo $helper->__("no Reviews & Comments"); ?></div>
<?php 							}
								foreach($reviews as $review){
									$reviewid = $review->getReviewId();
									$allpro = Mage::getModel("catalog/product")->load($review->getEntityPkValue());
									$productcity = Mage::getModel("catalog/product")->load($allpro["entity_id"]);	?>
								<div class="review <?php if($check_for_last_review == $review_count) echo 'wk_review_last'?>">
									<div class="wk_dash_reviewblock wk_ratingwidth">
										<div class="wk_cp_rating_price">
											<h2 class="wk_label"><?php echo $helper->__("Price") ?> :</h2>
											<div class="ratingbox">
<?php 											$ratingP = Mage::getModel("rating/rating")->getCollection()->addFieldToFilter("rating_code",array("eq"=>"Price"));
												foreach($ratingP as $rating)
													$ratingid = $rating->getRatingId();
												$_rating = Mage::getModel("rating/rating_option_vote")->getCollection()		
															->addFieldToFilter("review_id",array("eq"=>$reviewid))
															->addFieldToFilter("rating_id",array("eq"=>$ratingid));
												foreach($_rating as $rate)
													$percentage = $rate->getPercent();		?>
												<div class="rating" style="width:<?php echo ceil($percentage);?>%;"></div>
											</div>
										</div>
										<div class="wk_cp_rating">
											<h2 class="wk_label"><?php echo $helper->__("Value") ?> :</h2>
											<div class="ratingbox" >
<?php 											$ratingV = Mage::getModel("rating/rating")->getCollection()->addFieldToFilter("rating_code",array("eq"=>"Value"));
												foreach($ratingV as $rating)
													$ratingid = $rating->getRatingId();
												$_rating = Mage::getModel("rating/rating_option_vote")->getCollection()		
															->addFieldToFilter("review_id",array("eq"=>$reviewid))
															->addFieldToFilter("rating_id",array("eq"=>$ratingid));
												foreach($_rating as $rate)
													$percentage = $rate->getPercent(); 	?>
												<div class="rating" style="width:<?php echo ceil($percentage);?>%;"></div>
											</div>
										</div>
										<div class="wk_cp_rating">
											<h2 class="wk_label"><?php echo $helper->__("Quality") ?> :</h2>
											<div class="ratingbox">
											<?php 	$ratingQ = Mage::getModel("rating/rating")->getCollection()->addFieldToFilter("rating_code",array("eq"=>"Quality"));
												foreach($ratingQ as $rating)
													$ratingid = $rating->getRatingId();
												$_rating = Mage::getModel("rating/rating_option_vote")->getCollection()		
															->addFieldToFilter("review_id",array("eq"=>$reviewid))
															->addFieldToFilter("rating_id",array("eq"=>$ratingid));
												foreach($_rating as $rate)
														$percentage = $rate->getPercent();		?>
												<div class="rating" style="width:<?php echo ceil($percentage);?>%;"></div>
											</div>
										</div>
									</div>
									<div class="wk_dash_reviewblock wk_ratingcomment">
										<div class="wk_cp_comment">
											<p class="wk_product_label"><?php echo $helper->__("Product Name") ?> : </p>
											<p class="wk_product_content"><?php echo $productcity["name"]; ?></p>
										</div>
										<div class="wk_cp_comment">
											<p class="wk_product_label"><?php echo $helper->__("Comment By") ?> : </p>
											<p class="wk_product_content"><?php echo $review->getNickname()?></p>
										</div>
										<div class="wk_cp_comment">
											<p class="wk_product_label"><?php echo $helper->__("Summary")?> : </p>
											<p class="wk_product_content"><?php echo $review->getTitle()?></p>
										</div>
									</div>
									<div class="wk_dash_reviewblock">
<?php 									if($review->getStatusId() == 1)	{	?>
											<p class="statusapp"><?php echo $helper->__("Approved"); ?></p>
<?php 									}
										else 	{ 	?>
											<p class="statusunapp"><?php echo $helper->__("Unapproved"); ?></p>
<?php 									} 		?>
										<p class="wk_dash_label" style="display:inline-block;"><?php echo $helper->__("Review On"); ?>  : </p>
										<p class="textcolorpro"> <?php print_r(trim($review->getCreatedAt())); ?></p>
<?php 									$c++;	?>
									</div>
								</div>
<?php 								$check_for_last_review++;
								}								
							}		?>	
						</div>
					</div>
					<div class="fieldset">
						<h2 class="legend"><?php echo $helper->__("Sales Chart") ?></h2>	
						<!-- <div class="example-plot" id="chart2" style="width:593px;height:400px;"></div> -->
						<canvas class="example-plot" id="chart2" height="400" width="593"></canvas>
					</div>
				</div>
			</div>
			<div id="ask_data"> 
				<div class="modal_header">
					<h3><?php echo $helper->__("Ask Question to Admin") ?>..</h3>
					<span class="wk_close">x</span>
					<span style="clear:both;"></span>
				</div>
				<form id="ask_form" method="post" >
					<span class="label"><?php echo $helper->__("Subject") ?> :</span>
					<input type="text" name="subject" class="querysubject"/>
					<span class="label"> <?php echo $helper->__("Ask") ?> :</span>
					<textarea  name="ask" class="queryquestion"></textarea>
					<input type="hidden" name="seller-id" value="<?php echo Mage::getSingleton("customer/session")->getCustomerId();?>"/>
					<div class="modal_footer">
						<span class="error"></span>
						<input type="reset" value="<?php echo $helper->__("Reset") ?>" id="resetbtn"/>
						<input type="button" value="<?php echo $helper->__("Ask") ?>" id="askbtn"/>
						<span style="clear:both;"></span>
					</div>
				</form>
			</div>
			<script type="text/javascript">
				jQuery(document).ready(function(){
				    var data = JSON.parse('<?php echo Mage::getModel("customerpartner/saleslist")->getMonthlysale() ?>');
					var lineChartData = {
						labels : ["January","February","March","April","May","June","July","August","September","October","November","December"],
						datasets :  [{	fillColor : "rgba(220,220,220,0.5)",
										strokeColor : "rgba(220,220,220,1)",
										pointColor : "rgba(220,220,220,1)",
										pointStrokeColor : "#fff",
										data : [parseInt(data[1]),parseInt(data[2]),parseInt(data[3]),parseInt(data[4]),parseInt(data[5]),parseInt(data[6]),parseInt(data[7]),parseInt(data[8]),parseInt(data[9]),parseInt(data[10]),parseInt(data[11]),parseInt(data[12])]
									}]				
					}
					var myLine = new Chart(document.getElementById("chart2").getContext("2d")).Line(lineChartData);


					jQuery(".wrapper").append(jQuery("#ask_data"));
					jQuery(".askque").click(function(){
						jQuery("#ask_form input,#ask_form textarea").removeClass("error_border");
						jQuery(".page").css("opacity","0.4");
						jQuery("#ask_data").show();
					});
					jQuery(".wk_close").click(function(){
						jQuery(".page").css("opacity","1");
						jQuery("#resetbtn").trigger("click");
						jQuery("#ask_data").hide();
					});
					jQuery("#askbtn").click(function(){
						var f = 0;
						jQuery("#ask_form input,#ask_form textarea").each(function(){
							if(jQuery(this).val() == ""){
								jQuery(this).addClass("error_border");
								f++;
							}
						});
						if(f > 0){
							jQuery("#ask_form .error").text("<?php echo $helper->__('Fill all the fields') ?>").slideDown("slow").delay(2000).slideUp("slow");
						}
						else 	{	
							jQuery("#ask_data").addClass("mail_procss");
							jQuery.ajax({
								url:"<?php echo Mage::getBaseUrl();?>customerpartner/customeraccount/askquestion",
								data:jQuery("#ask_form").serialize(),
								type:"post",
								dataType:"json",
								success:function(d){
									jQuery("#ask-data").removeClass("mail_procss");
									alert("<?php echo $helper->__('Mail Send') ?>");
									jQuery(".wk_close,#resetbtn").trigger("click");
									jQuery("#ask_form").remove();
									jQuery(".askque").remove();
								}
							});
						}
					});
				});
			</script>
			<div class="button-set buttonarea">
				<p class="headingbackindex">
					<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo;<?php echo $helper->__("Back") ?></a>
				</p>
			</div>
<?php 	}
		else 	{
			Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getBaseUrl()."customer/account/edit/");
		    Mage::getSingleton("core/session")->addNotice($helper->__("To add product please request for become partner with us"));
		}